const mutationTypes = {
    SET_STORIES: 'SET_STORIES',
    SET_DATAS_FETCHED: 'SET_DATAS_FETCHED',
    SET_ONBOARDED: 'SET_ONBOARDED',
    SET_DIGITALVALUE: 'SET_DIGITALVALUE',
    SET_PERCENTEVALUE: 'SET_PERCENTEVALUE',
    SET_ANIMATED: 'SET_ANIMATED',
    SET_CURRENT_STORY: 'SET_CURRENT_STORY'
};

module.exports = mutationTypes;
